version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yarn-workspaces-demo-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
    # Uncomment if your app needs ports
    # ports:
    #   - "3000:3000"
    
  # Example of development setup
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.yarn
    command: sh -c "corepack enable && yarn install && yarn dev"
    environment:
      NODE_ENV: development
    # Uncomment if your app needs ports
    # ports:
    #   - "3000:3000"
